server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Task1
          uri: http://localhost:8081/
          predicates:
            - Path=/notes/**
